### ISSUE TITLE
「【依頼】ChatSpace挙動確認」

### ISSUE THREAD

**Issue by yjy00** [yjy00/chat-space#10]
54.199.80.151

**Comment by mo1015** [comment]
ご提出ありがとうございます‼︎
問題なく正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう（^^）
今後、実装に関するご質問がありましたら、テックコネクトにてメンターにご確認をお願いします！
